# Generated by Django 5.1.6 on 2025-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='reviewer',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
