# Generated by Django 5.1.6 on 2025-03-01 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_resume_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResumeImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.improvementarea')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvements', to='forum.resume')),
            ],
            options={
                'unique_together': {('resume', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ResumeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improvement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.resumeimprovement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'improvement')},
            },
        ),
    ]
